//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;

namespace SmartPayService
{
    public interface IPaymentPortTypeClient
    {
        Task<PaymentResult> authorise3dAsync(PaymentRequest3d paymentRequest3d);
        Task<PaymentResult> authoriseAsync(PaymentRequest paymentRequest);
        Task<ModificationResult> authoriseReferralAsync(ModificationRequest modificationRequest);
        Task<BalanceCheckResult> balanceCheckAsync(BalanceCheckRequest request);
        Task<ModificationResult> cancelAsync(ModificationRequest modificationRequest);
        Task<ModificationResult> cancelOrRefundAsync(ModificationRequest modificationRequest);
        Task<ModificationResult> captureAsync(ModificationRequest modificationRequest);
        Task<PaymentResult> checkFraudAsync(PaymentRequest paymentRequest);
        Task CloseAsync();
        Task<DirectDebitResponse> directdebitAsync(DirectDebitRequest request);
        Task<FundTransferResult> fundTransferAsync(FundTransferRequest request);
        Task OpenAsync();
        Task<ModificationResult> refundAsync(ModificationRequest modificationRequest);
        Task<PaymentResult> refundWithDataAsync(PaymentRequest request);
    }
}